[tools]
# 固定 Go 版本（可按需调整次版本）
go = "1.22"
# 静态检查工具（可选）
golangci-lint = "1.59.0"

[tasks.bootstrap]
run = "go mod tidy"

[tasks.test]
run = "go test ./..."

[tasks.lint]
run = "golangci-lint run"

[tasks.run-gateway]
env = { HTTP_ADDR = ":8081" }
run = "go run ./services/gateway"

[tasks.es-up]
run = "docker compose -f docker/es/docker-compose.yml up -d"

[tasks.es-down]
run = "docker compose -f docker/es/docker-compose.yml down -v"

[tasks.run-gateway-es]
env = { HTTP_ADDR = ":8081", KB_BACKEND = "es", ES_ADDRS = "http://localhost:9200", ES_INDEX = "kb_docs", FEATURE_RPC = "true", TICKET_RPC_ADDR = "127.0.0.1:8201", KB_RPC_ADDR = "127.0.0.1:8202", AI_RPC_ADDR = "127.0.0.1:8203" }
run = "go run ./services/gateway"

# RPC 独立运行（可用于本地联调）
[tasks.run-ticket-rpc]
run = "go run ./rpc/ticket"

[tasks.run-kb-rpc]
run = "go run ./rpc/kb"

[tasks.run-ai-rpc]
run = "go run ./rpc/ai"
