// Code generated by Kitex v0.14.1. DO NOT EDIT.

package ticketservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	common "github.com/gogogo1024/assist-fusion/kitex_gen/common"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateTicket(ctx context.Context, title string, desc string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error)
	GetTicket(ctx context.Context, id string, callOptions ...callopt.Option) (r *common.Ticket, err error)
	ListTickets(ctx context.Context, callOptions ...callopt.Option) (r []*common.Ticket, err error)
	Assign(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error)
	Resolve(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error)
	Escalate(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error)
	Reopen(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error)
	GetCycles(ctx context.Context, id string, callOptions ...callopt.Option) (r []*common.TicketCycle, err error)
	GetEvents(ctx context.Context, id string, callOptions ...callopt.Option) (r []*common.TicketEvent, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTicketServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTicketServiceClient struct {
	*kClient
}

func (p *kTicketServiceClient) CreateTicket(ctx context.Context, title string, desc string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTicket(ctx, title, desc, note)
}

func (p *kTicketServiceClient) GetTicket(ctx context.Context, id string, callOptions ...callopt.Option) (r *common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTicket(ctx, id)
}

func (p *kTicketServiceClient) ListTickets(ctx context.Context, callOptions ...callopt.Option) (r []*common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTickets(ctx)
}

func (p *kTicketServiceClient) Assign(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Assign(ctx, id, note)
}

func (p *kTicketServiceClient) Resolve(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Resolve(ctx, id, note)
}

func (p *kTicketServiceClient) Escalate(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Escalate(ctx, id, note)
}

func (p *kTicketServiceClient) Reopen(ctx context.Context, id string, note string, callOptions ...callopt.Option) (r *common.Ticket, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Reopen(ctx, id, note)
}

func (p *kTicketServiceClient) GetCycles(ctx context.Context, id string, callOptions ...callopt.Option) (r []*common.TicketCycle, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCycles(ctx, id)
}

func (p *kTicketServiceClient) GetEvents(ctx context.Context, id string, callOptions ...callopt.Option) (r []*common.TicketEvent, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetEvents(ctx, id)
}
