// Code generated by Kitex v0.14.1. DO NOT EDIT.

package kbservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	common "github.com/gogogo1024/assist-fusion/kitex_gen/common"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddDoc(ctx context.Context, title string, content string, callOptions ...callopt.Option) (r *common.KBDoc, err error)
	UpdateDoc(ctx context.Context, id string, title string, content string, callOptions ...callopt.Option) (r *common.KBDoc, err error)
	DeleteDoc(ctx context.Context, id string, callOptions ...callopt.Option) (err error)
	Search(ctx context.Context, query string, limit int32, callOptions ...callopt.Option) (r []*common.SearchItem, err error)
	Info(ctx context.Context, callOptions ...callopt.Option) (r map[string]string, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKBServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKBServiceClient struct {
	*kClient
}

func (p *kKBServiceClient) AddDoc(ctx context.Context, title string, content string, callOptions ...callopt.Option) (r *common.KBDoc, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddDoc(ctx, title, content)
}

func (p *kKBServiceClient) UpdateDoc(ctx context.Context, id string, title string, content string, callOptions ...callopt.Option) (r *common.KBDoc, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDoc(ctx, id, title, content)
}

func (p *kKBServiceClient) DeleteDoc(ctx context.Context, id string, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDoc(ctx, id)
}

func (p *kKBServiceClient) Search(ctx context.Context, query string, limit int32, callOptions ...callopt.Option) (r []*common.SearchItem, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, query, limit)
}

func (p *kKBServiceClient) Info(ctx context.Context, callOptions ...callopt.Option) (r map[string]string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Info(ctx)
}
