// Code generated by Kitex v0.14.1. DO NOT EDIT.
package kbservice

import (
	server "github.com/cloudwego/kitex/server"
	kb "github.com/gogogo1024/assist-fusion/kitex_gen/kb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kb.KBService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler kb.KBService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
