// Code generated by Kitex v0.14.1. DO NOT EDIT.

package aiservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ai "github.com/gogogo1024/assist-fusion/kitex_gen/ai"
	common "github.com/gogogo1024/assist-fusion/kitex_gen/common"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Embeddings": kitex.NewMethodInfo(
		embeddingsHandler,
		newAIServiceEmbeddingsArgs,
		newAIServiceEmbeddingsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newAIServiceChatArgs,
		newAIServiceChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aIServiceServiceInfo                = NewServiceInfo()
	aIServiceServiceInfoForClient       = NewServiceInfoForClient()
	aIServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aIServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aIServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AIService"
	handlerType := (*ai.AIService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func embeddingsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceEmbeddingsArgs)
	realResult := result.(*ai.AIServiceEmbeddingsResult)
	success, err := handler.(ai.AIService).Embeddings(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.ServiceError:
			realResult.Err = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newAIServiceEmbeddingsArgs() interface{} {
	return ai.NewAIServiceEmbeddingsArgs()
}

func newAIServiceEmbeddingsResult() interface{} {
	return ai.NewAIServiceEmbeddingsResult()
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceChatArgs)
	realResult := result.(*ai.AIServiceChatResult)
	success, err := handler.(ai.AIService).Chat(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.ServiceError:
			realResult.Err = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newAIServiceChatArgs() interface{} {
	return ai.NewAIServiceChatArgs()
}

func newAIServiceChatResult() interface{} {
	return ai.NewAIServiceChatResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Embeddings(ctx context.Context, req *common.EmbeddingRequest) (r *common.EmbeddingResponse, err error) {
	var _args ai.AIServiceEmbeddingsArgs
	_args.Req = req
	var _result ai.AIServiceEmbeddingsResult
	if err = p.c.Call(ctx, "Embeddings", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Err != nil:
		return r, _result.Err
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Chat(ctx context.Context, req *ai.ChatRequest) (r *ai.ChatResponse, err error) {
	var _args ai.AIServiceChatArgs
	_args.Req = req
	var _result ai.AIServiceChatResult
	if err = p.c.Call(ctx, "Chat", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Err != nil:
		return r, _result.Err
	}
	return _result.GetSuccess(), nil
}
